version: "3"
services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - "${PWD}/data/postgres/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  wiki:
    build: ./build/wikijs
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - "${PWD}/data/wikijs/data:/home/wikijs/data"
      - "${PWD}/data/wikijs/repo:/home/wikijs/repos"
    ports:
      - "8080:80"

