version: "3"
services:
  postgres:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wikijs
      - MONGO_INITDB_ROOT_PASSWORD=wikijs
      - MONGO_INITDB_DATABASE=wikijs
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  wiki:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "8181:3000"
volumes:
  postgres:
    driver: local
